### ISSUE TITLE
License Metadata

### ISSUE THREAD

**Issue by ksuderman** [lappsgrid-services/org.anc.lapps.stanford#12]
The metadata returned by the `getMetadata` method should return the Stanford license (in reStructuredText) rather than the wrapper license.

**Comment by ksuderman** [comment]
Nope it shouldn't.  This is changed in the 1.1.0 schema.

**Comment by keighrim** [comment]
I see that schema 1.1.0 [would add](https://github.com/lapps/schemata/commit/21b312f6760af9b6e3b112300d9fd934d622b811) `licenseDesc` field in metadata. 
But none of existing services are utilizing `licenseDesc` field for the moment, and no related libraries ([[1]](https://github.com/lapps/org.lappsgrid.annotations/issues/7), [[2]](https://github.com/lapps/org.lappsgrid.metadata/issues/9)) are supporting it, neither. 
Before, we used `license` field to store the wrapper license, but I wonder how those two should be set after 1.1.0.

**Comment by ksuderman** [comment]
The *license* field should be the URI for the license and *licenseDesc* is a human readable form of the license, likely in markdown to be displayed in Galaxy.  At the UPenn meeting we started abusing the *license* field to store the markdown and we should likely stop doing that.

**Comment by keighrim** [comment]
So, _license_ for the URI to the tool (wrapper) license, and _licenseDesc_ for any additional information including the license of the actual tool that wrapped in (preferably) markdown format, right?
